package com.example.MPI_Project.security_access_rights_tests;// Generated by Selenium IDE

import com.example.MPI_Project.testHelpers.TestUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AccessRightsTest {
    private WebDriver driver;
    Wait<WebDriver> wait;

    @Before
    public void setUp() {
        driver = TestUtils.GetDriver();
        wait = new WebDriverWait(driver, 5, 1000);
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void adminAccessRightsTest() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("admin");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("admin");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector("span")).click();
        driver.findElement(By.cssSelector("span")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("admin"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).getText(), is("Бухгалтер"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Консультант"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Управляющий"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Сотрудник"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Охранник"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_adminButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Пользователи"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

    @Test
    public void accountAccessRightsTest() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("account");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("account");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector("p:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("account"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).getText(), is("Бухгалтер"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

    @Test
    public void consultantAccessRightsTest() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("consultant");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("consultant");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector("p:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("consultant"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Консультант"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

    @Test
    public void managerAccessRightsTest() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("manager");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("manager");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector("span")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("manager"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Управляющий"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

    @Test
    public void securityAccessRightsTest() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("security");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("security");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector("span")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("security"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Охранник"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

    @Test
    public void workmanAccessRightsTest() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1) > form")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("workman");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("workman");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector("p:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("workman"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Сотрудник"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

}
