package com.example.MPI_Project.security_access_rights_tests;// Generated by Selenium IDE

import com.example.MPI_Project.testHelpers.AuthTestHelper;
import com.example.MPI_Project.testHelpers.TestUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AccessRightsTest {
    private WebDriver driver;
    Wait<WebDriver> wait;

    @Before
    public void setUp() {
        driver = TestUtils.getDriver();
        wait = new WebDriverWait(driver, 5, 1000);
    }

    @After
    public void tearDown() {
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
        driver.quit();
    }

    @Test
    public void adminAccessRightsTest() {
        AuthTestHelper.auth(driver,"admin", "admin");
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).getText(), is("Бухгалтер"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("Консультант"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("Управляющий"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("Сотрудник"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Охранник"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_adminButton")).click();
        driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Пользователи"));
    }

    @Test
    public void accountAccessRightsTest() {
        AuthTestHelper.auth(driver,"account", "account");
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector(".styled-table:nth-child(1) tr:nth-child(1) > td:nth-child(1)")).getText(), is("Бухгалтер"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
    }

    @Test
    public void consultantAccessRightsTest() {
        AuthTestHelper.auth(driver,"consultant", "consultant");
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("Консультант"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
    }

    @Test
    public void managerAccessRightsTest() {
        AuthTestHelper.auth(driver,"manager", "manager");
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("Управляющий"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
    }

    @Test
    public void securityAccessRightsTest() {
        AuthTestHelper.auth(driver,"security", "security");
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("Охранник"));
    }

    @Test
    public void workmanAccessRightsTest() {
        AuthTestHelper.auth(driver,"workman", "workman");
        driver.findElement(By.name("task_accButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_conButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("Сотрудник"));
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_secButton")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Эта страница недоступна"));
    }

}
