package com.example.MPI_Project.functional_tests;// Generated by Selenium IDE

import com.example.MPI_Project.testHelpers.TestDataFiller;
import com.example.MPI_Project.testHelpers.TestUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class ManagerFunctionalTest {
    private WebDriver driver;
    Wait<WebDriver> wait;
    TestDataFiller testDataFiller;

    @Before
    public void setUp() {
        driver = TestUtils.GetDriver();
        wait = new WebDriverWait(driver, 5, 1000);
        testDataFiller = new TestDataFiller();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void createNewTask() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("manager");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("manager");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        while(!driver.findElements(By.cssSelector("span")).isEmpty()){
            driver.findElement(By.name("task_deleteButton")).click();
        }
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
        driver.findElement(By.name("newTask_name")).click();
        driver.findElement(By.name("newTask_name")).sendKeys("Тестовая задача");
        driver.findElement(By.name("newTask_deadline")).click();
        driver.findElement(By.name("newTask_deadline")).sendKeys("2021-12-03");
        driver.findElement(By.cssSelector("p:nth-child(3) > #taskStatus_wip")).click();
        driver.findElement(By.name("newTask_description")).click();
        driver.findElement(By.name("newTask_description")).sendKeys("Описание тестовой задачи");
        driver.findElement(By.name("newTask_workman")).click();
        driver.findElement(By.name("newTask_workman")).sendKeys("workman");
        driver.findElement(By.name("newTask_description")).click();
        driver.findElement(By.name("newTask_description")).click();
        driver.findElement(By.name("newTask_description")).click();
        driver.findElement(By.cssSelector("td:nth-child(2) p:nth-child(6) > input:nth-child(1)")).click();
        driver.findElement(By.cssSelector("span")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("Тестовая задача"));
        driver.findElement(By.cssSelector("i")).click();
        assertThat(driver.findElement(By.cssSelector("i")).getText(), is("Выполняется"));
        driver.findElement(By.cssSelector("td > .colTask")).click();
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

    @Test
    public void editTask() {
        driver.get("http://localhost:8080/main");
        driver.manage().window().setSize(new Dimension(1530,829));
        driver.findElement(By.name("task_loginButton")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("manager");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("manager");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_managButton")).click();
        driver.findElement(By.cssSelector("tr > .colTask:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("Тестовая задача"));
        driver.findElement(By.cssSelector(".colTask:nth-child(3)")).click();
        assertThat(driver.findElement(By.cssSelector("i")).getText(), is("Выполняется"));
        driver.findElement(By.name("task_changeButton")).click();
        driver.findElement(By.name("task_name")).click();
        driver.findElement(By.name("task_name")).clear();
        driver.findElement(By.name("task_name")).sendKeys("Отредактированная задача");
        driver.findElement(By.id("taskStatus_stopped")).click();
        driver.findElement(By.name("task_description")).click();
        driver.findElement(By.name("task_description")).click();
        driver.findElement(By.name("task_deadline")).click();
        driver.findElement(By.name("task_description")).clear();
        driver.findElement(By.name("task_description")).sendKeys("Отредактированное описание тестовой задачи");
        driver.findElement(By.name("task_deadline")).click();
        driver.findElement(By.name("task_deadline")).sendKeys("2021-12-05");
        driver.findElement(By.cssSelector("p:nth-child(7) > input")).click();
        driver.findElement(By.cssSelector("tr > .colTask:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("Отредактированная задача"));
        driver.findElement(By.cssSelector("i")).click();
        assertThat(driver.findElement(By.cssSelector("i")).getText(), is("Приостановлено"));
        driver.findElement(By.cssSelector("th:nth-child(3)")).click();
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
    }

}
