package com.example.MPI_Project.functional_tests;// Generated by Selenium IDE

import com.example.MPI_Project.testHelpers.AuthTestHelper;
import com.example.MPI_Project.testHelpers.TestUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class WorkmanFunctionalTest {
    private WebDriver driver;

    @Before
    public void setUp() {
        driver = TestUtils.getDriver();
        AuthTestHelper.auth(driver,"workman", "workman");
    }

    @After
    public void tearDown() {
        driver.findElement(By.name("exitButton")).click();
        driver.findElement(By.name("task_logoutButton")).click();
        driver.findElement(By.name("exitButton")).click();
        driver.quit();
    }

    @Test
    public void editStatusTask() {
        driver.findElement(By.name("task_workButton")).click();
        driver.findElement(By.name("task_changeButton")).click();
        driver.findElement(By.cssSelector("i")).click();
        driver.findElement(By.cssSelector("i")).click();
        assertThat(driver.findElement(By.cssSelector("i")).getText(), is("Приостановлено"));
        driver.findElement(By.cssSelector("form > p:nth-child(2)")).click();
        driver.findElement(By.id("taskStatus_problems")).click();
        driver.findElement(By.cssSelector("p:nth-child(5) > input")).click();
        driver.findElement(By.cssSelector(".colTask:nth-child(3)")).click();
        assertThat(driver.findElement(By.cssSelector("i")).getText(), is("Возникли проблемы"));
        driver.findElement(By.cssSelector("td > .colTask")).click();
    }

}
